-- Generated by Level Director X v1.1.0 on mer set 18 18:59:08 2019 --
require("lib.LD_HelperX")
local M={}
-----------------------------------
function M:loadAssets()
-----------------------------------
	local assets={}
	assets.spriteSheetData={}
	assets['redBrick - Copia_0']={file ='redBrick - Copia.png',name='redBrick - Copia_0',class='',aX=0.5,aY=0.5,width=100,height=40,frame=0,spriteSheetName='redBrick - Copia',frameCount=1,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Rectangle',shape={},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	return assets
end -- loadAssets 

------------------------------------------
function M:createLevel(LD_Helper_Instance)
------------------------------------------
	local instance=LD_Helper_Instance
	local objProps={}
	local level={}
    local obj=nil
	local k=0
	local objects = nil 
	if (instance.viewGroup == nil) then
		level.view=display.newGroup() 
	else
		level.view=instance.viewGroup
	end
	level.view.anchorChildren =false 
	display.setDefault( 'background',102/255,102/255,102/255,255/255)
	display.setDefault( "anchorX",0.5 )
	display.setDefault( "anchorY",0.5 )	
	display.setDrawMode("wireframe",false)
	level.name='Level01' 
	-- Load Assets
	level.assets=self:loadAssets()
	-- Physics properties
	physics.setGravity(0,9.8) 
	physics.setDrawMode('normal')
	physics.setPositionIterations(8)	
	physics.setVelocityIterations(3)	
	level.parallaxEnabled=false
	-- Layers --
	level.layers={} 
	---- Layer 1 ------------------------------------------------------------------------------------
	level.layers['Layer 1']={} 
	level.layers['Layer 1'].view=display.newGroup() 
	level.layers['Layer 1'].name='Layer 1' 
	if (level.parallaxEnabled) then
		level.layers['Layer 1'].speed={x=0,y=0}
		level.layers['Layer 1'].repeated=false
		level.layers['Layer 1'].cullingMethod=0
	else
		level.layers['Layer 1'].cullingMethod=0 
	end
	level.layers['Layer 1'].objects={} 
	objects = {
	{name='redBrick - Copia_0',objType='LDImage',class='',width=100,height=40,x=98,y=292,xScale=1*1,yScale=1*1,assetName='redBrick - Copia_0',
		userProps = {},
		},
	{name='redBrick - Copia_2',objType='LDImage',class='',width=100,height=40,x=242,y=292,xScale=1*1,yScale=1*1,assetName='redBrick - Copia_0',
		userProps = {},
		},
	{name='redBrick - Copia_3',objType='LDImage',class='',width=100,height=40,x=386,y=292,xScale=1*1,yScale=1*1,assetName='redBrick - Copia_0',
		userProps = {},
		},
	{name='redBrick - Copia_4',objType='LDImage',class='',width=100,height=40,x=530,y=292,xScale=1*1,yScale=1*1,assetName='redBrick - Copia_0',
		userProps = {},
		},
	{name='redBrick - Copia_5',objType='LDImage',class='',width=100,height=40,x=178,y=404,xScale=1*1,yScale=1*1,assetName='redBrick - Copia_0',
		userProps = {},
		},
	{name='redBrick - Copia_6',objType='LDImage',class='',width=100,height=40,x=322,y=404,xScale=1*1,yScale=1*1,assetName='redBrick - Copia_0',
		userProps = {},
		},
	{name='redBrick - Copia_7',objType='LDImage',class='',width=100,height=40,x=466,y=404,xScale=1*1,yScale=1*1,assetName='redBrick - Copia_0',
		userProps = {},
		},
	{name='redBrick - Copia_8',objType='LDImage',class='',width=100,height=40,x=114,y=500,xScale=1*1,yScale=1*1,assetName='redBrick - Copia_0',
		userProps = {},
		},
	{name='redBrick - Copia_9',objType='LDImage',class='',width=100,height=40,x=530,y=500,xScale=1*1,yScale=1*1,assetName='redBrick - Copia_0',
		userProps = {},
		},
	{name='redBrick - Copia_10',objType='LDImage',class='',width=100,height=40,x=322,y=500,xScale=1*1,yScale=1*1,assetName='redBrick - Copia_0',
		userProps = {},
		},
	{name='redBrick - Copia_11',objType='LDImage',class='',width=100,height=40,x=210,y=596,xScale=1*1,yScale=1*1,assetName='redBrick - Copia_0',
		userProps = {},
		},
	{name='redBrick - Copia_1',objType='LDImage',class='',width=100,height=40,x=434,y=596,xScale=1*1,yScale=1*1,assetName='redBrick - Copia_0',
		userProps = {},
		},
	{name='ellipse_13',objType='LDEllipse',class='',width=80,height=80,x=320,y=40,xScale=1*1,yScale=1*1,assetName='',
		styleProps={radius=40,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=255/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=2,fillAssetName='redBrick - Copia_0',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		userProps = {},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['Layer 1'], objProps ,level.assets)
		if (obj and objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['Layer 1'])
	--level.ldVersion=1.1.0	-- Level Director Version
	-- Parallax (after layers)
	level.canvasWidth=640
	level.canvasHeight=960
	if level.parallaxEnabled then
		level.parallaxInfinite=false
		level.parallaxDamping=1
		instance:createParallax(level)
	end
	return level
end -- createLevel
return M

