-- Generated by Level Director X v1.0.4 on Tue Jul 26 15:38:40 2016 --
require("lib.LD_HelperX")
local M={}
-----------------------------------
function M:loadAssets()
-----------------------------------
	local assets={}
	assets.spriteSheetData={}
	assets.spriteSheetData['bg_tileset']={}
	assets.spriteSheetData['bg_tileset'].frames ={
		{x=0,y=0,width=256,height=256},
		{x=256,y=0,width=256,height=256},
		{x=512,y=0,width=256,height=256},
		{x=768,y=0,width=256,height=256},
		{x=0,y=256,width=256,height=256},
		{x=256,y=256,width=256,height=256},
		{x=512,y=256,width=256,height=256},
		{x=768,y=256,width=256,height=256},
		{x=0,y=512,width=256,height=256},
		{x=256,y=512,width=256,height=256},
		{x=512,y=512,width=256,height=256},
		{x=768,y=512,width=256,height=256},
		{x=0,y=768,width=256,height=256},
		{x=256,y=768,width=256,height=256},
		{x=512,y=768,width=256,height=256},
		{x=768,y=768,width=256,height=256},
		{x=0,y=1024,width=256,height=256},
		{x=256,y=1024,width=256,height=256},
		{x=512,y=1024,width=256,height=256},
		{x=768,y=1024,width=256,height=256},
		{x=0,y=1280,width=256,height=256},
		{x=256,y=1280,width=256,height=256},
		{x=512,y=1280,width=256,height=256},
		{x=768,y=1280,width=256,height=256},
		{x=0,y=1536,width=256,height=256},
		{x=256,y=1536,width=256,height=256},
		{x=512,y=1536,width=256,height=256},
		{x=768,y=1536,width=256,height=256},
		sheetContentWidth=1024,
		sheetContentHeight=2048
	}
	assets.spriteSheetData['run_shoot']={}
	assets.spriteSheetData['run_shoot'].frames ={
		{x=0,y=0,width=567,height=556},
		{x=567,y=0,width=567,height=556},
		{x=1134,y=0,width=567,height=556},
		{x=0,y=556,width=567,height=556},
		{x=567,y=556,width=567,height=556},
		{x=1134,y=556,width=567,height=556},
		{x=0,y=1112,width=567,height=556},
		{x=567,y=1112,width=567,height=556},
		{x=1134,y=1112,width=567,height=556},
		sheetContentWidth=2048,
		sheetContentHeight=2048
	}
	assets['space_bg2_0']={file ='space_bg2.png',name='space_bg2_0',class='',aX=0.5,aY=0.5,width=1024,height=512,frame=0,spriteSheetName='space_bg2',frameCount=1,
		 }
	assets['BGTile (1)_png']={file ='bg_tileset.png',name='BGTile (1)_png',class='',aX=0.5,aY=0.5,width=256,height=256,frame=3,spriteSheetName='bg_tileset',frameCount=28,
		 }
	assets['BGTile (3)_png']={file ='bg_tileset.png',name='BGTile (3)_png',class='',aX=0.5,aY=0.5,width=256,height=256,frame=5,spriteSheetName='bg_tileset',frameCount=28,
		 }
	assets['Fence (1)_png']={file ='bg_tileset.png',name='Fence (1)_png',class='',aX=0.5,aY=0.5,width=256,height=256,frame=10,spriteSheetName='bg_tileset',frameCount=28,
		 }
	assets['Fence (2)_png']={file ='bg_tileset.png',name='Fence (2)_png',class='',aX=0.5,aY=0.5,width=256,height=256,frame=11,spriteSheetName='bg_tileset',frameCount=28,
		 }
	assets['Fence (3)_png']={file ='bg_tileset.png',name='Fence (3)_png',class='',aX=0.5,aY=0.5,width=256,height=256,frame=12,spriteSheetName='bg_tileset',frameCount=28,
		 }
	assets['Spike_png']={file ='bg_tileset.png',name='Spike_png',class='',aX=0.5,aY=0.5,width=256,height=256,frame=13,spriteSheetName='bg_tileset',frameCount=28,
		 }
	assets['Tile (1)_png']={file ='bg_tileset.png',name='Tile (1)_png',class='',aX=0.5,aY=0.5,width=256,height=256,frame=14,spriteSheetName='bg_tileset',frameCount=28,
		 }
	assets['Tile (4)_png']={file ='bg_tileset.png',name='Tile (4)_png',class='',aX=0.5,aY=0.5,width=256,height=256,frame=17,spriteSheetName='bg_tileset',frameCount=28,
		 }
	assets['Tile (5)_png']={file ='bg_tileset.png',name='Tile (5)_png',class='',aX=0.5,aY=0.5,width=256,height=256,frame=18,spriteSheetName='bg_tileset',frameCount=28,
		 }
	assets['Tile (6)_png']={file ='bg_tileset.png',name='Tile (6)_png',class='',aX=0.5,aY=0.5,width=256,height=256,frame=19,spriteSheetName='bg_tileset',frameCount=28,
		 }
	assets['Tile (7)_png']={file ='bg_tileset.png',name='Tile (7)_png',class='',aX=0.5,aY=0.5,width=256,height=256,frame=20,spriteSheetName='bg_tileset',frameCount=28,
		 }
	assets['Tile (8)_png']={file ='bg_tileset.png',name='Tile (8)_png',class='',aX=0.5,aY=0.5,width=256,height=256,frame=21,spriteSheetName='bg_tileset',frameCount=28,
		 }
	assets['Tile (9)_png']={file ='bg_tileset.png',name='Tile (9)_png',class='',aX=0.5,aY=0.5,width=256,height=256,frame=22,spriteSheetName='bg_tileset',frameCount=28,
		 }
	assets['Tile (12)_png']={file ='bg_tileset.png',name='Tile (12)_png',class='',aX=0.5,aY=0.5,width=256,height=256,frame=25,spriteSheetName='bg_tileset',frameCount=28,
		 }
	assets['Tile (13)_png']={file ='bg_tileset.png',name='Tile (13)_png',class='',aX=0.5,aY=0.5,width=256,height=256,frame=26,spriteSheetName='bg_tileset',frameCount=28,
		 }
	assets['Tile (14)_png']={file ='bg_tileset.png',name='Tile (14)_png',class='',aX=0.5,aY=0.5,width=256,height=256,frame=27,spriteSheetName='bg_tileset',frameCount=28,
		 }
	assets['RunShoot (1)_png']={file ='run_shoot.png',name='RunShoot (1)_png',class='',aX=0.5,aY=0.5,width=567,height=556,frame=1,spriteSheetName='run_shoot',frameCount=9,
		sequenceData={{name='run',frames={ 1,2,3,4,5,6,7,8 },time =1000,loopCount=0,loopDirection='forward' },{name='idle',frames={ 9 },time =200,loopCount=0,loopDirection='forward' },},
		sequenceInfo={default='run',play=true },
		 }
	return assets
end -- loadAssets 

------------------------------------------
function M:createLevel(LD_Helper_Instance)
------------------------------------------
	local instance=LD_Helper_Instance
	local objProps={}
	local level={}
    local obj=nil
	local k=0
	local objects = nil 
	if (instance.viewGroup == nil) then
		level.view=display.newGroup() 
	else
		level.view=instance.viewGroup
	end
	level.view.anchorChildren =false 
	display.setDefault( 'background',130/255,130/255,130/255,255/255)
	display.setDefault( "anchorX",0.5 )
	display.setDefault( "anchorY",0.5 )	
	display.setDrawMode("wireframe",false)
	level.name='scene1_view' 
	-- Load Assets
	level.assets=self:loadAssets()
	-- Physics properties
	physics.setGravity(0,9.8) 
	physics.setDrawMode('hybrid')
	physics.setPositionIterations(8)	
	physics.setVelocityIterations(3)	
	level.parallaxEnabled=true
	level.Enemy=''
	-- Layers --
	level.layers={} 
	---- BG ------------------------------------------------------------------------------------
	level.layers['BG']={} 
	level.layers['BG'].view=display.newGroup() 
	level.layers['BG'].name='BG' 
	if (level.parallaxEnabled) then
		level.layers['BG'].speed={x=0.2,y=0}
		level.layers['BG'].repeated=true
		level.layers['BG'].cullingMethod=0
	else
		level.layers['BG'].cullingMethod=0 
	end
	level.layers['BG'].objects={} 
	objects = {
	{name='space_bg2_1',objType='LDImage',class='',width=1280,height=800,x=0,y=0,xScale=1.25*1,yScale=1.5625*1,assetName='space_bg2_0',
		rotation=0,enableDrag=false,anchorX=0,anchorY=0,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='space_bg2_2',objType='LDImage',class='',width=1280,height=800,x=1280,y=0,xScale=1.25*1,yScale=1.5625*1,assetName='space_bg2_0',
		rotation=0,enableDrag=false,anchorX=0,anchorY=0,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['BG'], objProps ,level.assets)
		if (objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['BG'])
	---- level ------------------------------------------------------------------------------------
	level.layers['level']={} 
	level.layers['level'].view=display.newGroup() 
	level.layers['level'].name='level' 
	if (level.parallaxEnabled) then
		level.layers['level'].speed={x=1,y=0}
		level.layers['level'].repeated=false
		level.layers['level'].cullingMethod=0
	else
		level.layers['level'].cullingMethod=0 
	end
	level.layers['level'].objects={} 
	objects = {
	{name='Tile (4)_9',objType='LDImage',class='',width=256,height=256,x=2688,y=288,xScale=1*1,yScale=1*1,assetName='Tile (4)_png',
		userProps = {},
		},
	{name='Tile (4)_10',objType='LDImage',class='',width=256,height=256,x=2688,y=544,xScale=1*1,yScale=1*1,assetName='Tile (4)_png',
		userProps = {},
		},
	{name='Tile (5)_4',objType='LDImage',class='',width=256,height=256,x=2944,y=544,xScale=1*1,yScale=1*1,assetName='Tile (5)_png',
		userProps = {},
		},
	{name='Tile (6)_5',objType='LDImage',class='',width=256,height=256,x=3712,y=288,xScale=1*1,yScale=1*1,assetName='Tile (6)_png',
		userProps = {},
		},
	{name='Tile (6)_6',objType='LDImage',class='',width=256,height=256,x=3712,y=544,xScale=1*1,yScale=1*1,assetName='Tile (6)_png',
		userProps = {},
		},
	{name='Tile (5)_7',objType='LDImage',class='',width=256,height=256,x=3200,y=544,xScale=1*1,yScale=1*1,assetName='Tile (5)_png',
		userProps = {},
		},
	{name='Tile (5)_8',objType='LDImage',class='',width=256,height=256,x=3200,y=288,xScale=1*1,yScale=1*1,assetName='Tile (5)_png',
		userProps = {},
		},
	{name='Tile (5)_9',objType='LDImage',class='',width=256,height=256,x=3456,y=544,xScale=1*1,yScale=1*1,assetName='Tile (5)_png',
		userProps = {},
		},
	{name='Tile (4)_11',objType='LDImage',class='',width=256,height=256,x=2688,y=32,xScale=1*1,yScale=1*1,assetName='Tile (4)_png',
		userProps = {},
		},
	{name='Tile (6)_15',objType='LDImage',class='',width=256,height=256,x=3712,y=32,xScale=1*1,yScale=1*1,assetName='Tile (6)_png',
		userProps = {},
		},
	{name='Spike_11',objType='LDImage',class='',width=256,height=256,x=3744,y=544,xScale=1*1,yScale=1*1,assetName='Spike_png',
		userProps = {},
		},
	{name='Spike_12',objType='LDImage',class='',width=256,height=256,x=3904,y=544,xScale=1*1,yScale=1*1,assetName='Spike_png',
		userProps = {},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['level'], objProps ,level.assets)
		if (objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['level'])
	---- platform ------------------------------------------------------------------------------------
	level.layers['platform']={} 
	level.layers['platform'].view=display.newGroup() 
	level.layers['platform'].name='platform' 
	if (level.parallaxEnabled) then
		level.layers['platform'].speed={x=1,y=0}
		level.layers['platform'].repeated=true
		level.layers['platform'].cullingMethod=0
	else
		level.layers['platform'].cullingMethod=0 
	end
	level.layers['platform'].objects={} 
	objects = {
	{name='Tile (13)_1',objType='LDImage',class='',width=256,height=256,x=128,y=800,xScale=1*1,yScale=1*1,assetName='Tile (13)_png',
		userProps = {},
		},
	{name='Tile (13)_2',objType='LDImage',class='',width=256,height=256,x=384,y=800,xScale=1*1,yScale=1*1,assetName='Tile (13)_png',
		userProps = {},
		},
	{name='Tile (13)_3',objType='LDImage',class='',width=256,height=256,x=640,y=800,xScale=1*1,yScale=1*1,assetName='Tile (13)_png',
		userProps = {},
		},
	{name='Tile (13)_4',objType='LDImage',class='',width=256,height=256,x=896,y=800,xScale=1*1,yScale=1*1,assetName='Tile (13)_png',
		userProps = {},
		},
	{name='Tile (13)_5',objType='LDImage',class='',width=256,height=256,x=1152,y=800,xScale=1*1,yScale=1*1,assetName='Tile (13)_png',
		userProps = {},
		},
	{name='Tile (13)_6',objType='LDImage',class='',width=256,height=256,x=1664,y=800,xScale=1*1,yScale=1*1,assetName='Tile (13)_png',
		userProps = {},
		},
	{name='Tile (13)_7',objType='LDImage',class='',width=256,height=256,x=2432,y=800,xScale=1*1,yScale=1*1,assetName='Tile (13)_png',
		userProps = {},
		},
	{name='Tile (13)_8',objType='LDImage',class='',width=256,height=256,x=1408,y=800,xScale=1*1,yScale=1*1,assetName='Tile (13)_png',
		userProps = {},
		},
	{name='Tile (13)_9',objType='LDImage',class='',width=256,height=256,x=2176,y=800,xScale=1*1,yScale=1*1,assetName='Tile (13)_png',
		userProps = {},
		},
	{name='Tile (13)_10',objType='LDImage',class='',width=256,height=256,x=1920,y=800,xScale=1*1,yScale=1*1,assetName='Tile (13)_png',
		userProps = {},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['platform'], objProps ,level.assets)
		if (objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['platform'])
	---- player ------------------------------------------------------------------------------------
	level.layers['player']={} 
	level.layers['player'].view=display.newGroup() 
	level.layers['player'].name='player' 
	if (level.parallaxEnabled) then
		level.layers['player'].speed={x=0,y=0}
		level.layers['player'].repeated=false
		level.layers['player'].cullingMethod=0
	else
		level.layers['player'].cullingMethod=0 
	end
	level.layers['player'].objects={} 
	objects = {
	{name='RunShoot (1)_1',objType='LDImage',class='',width=151,height=140,x=139,y=614,xScale=0.266314*1,yScale=0.251799*1,assetName='RunShoot (1)_png',
		userProps = {},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['player'], objProps ,level.assets)
		if (objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['player'])
	---- FG ------------------------------------------------------------------------------------
	level.layers['FG']={} 
	level.layers['FG'].view=display.newGroup() 
	level.layers['FG'].name='FG' 
	if (level.parallaxEnabled) then
		level.layers['FG'].speed={x=4,y=0}
		level.layers['FG'].repeated=true
		level.layers['FG'].cullingMethod=0
	else
		level.layers['FG'].cullingMethod=0 
	end
	level.layers['FG'].objects={} 
	objects = {
	{name='Spike_1',objType='LDImage',class='',width=256,height=448,x=2432,y=576,xScale=1*1,yScale=1.75*1,assetName='Spike_png',
		userProps = {},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['FG'], objProps ,level.assets)
		if (objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['FG'])
	---- hud ------------------------------------------------------------------------------------
	level.layers['hud']={} 
	level.layers['hud'].view=display.newGroup() 
	level.layers['hud'].name='hud' 
	if (level.parallaxEnabled) then
		level.layers['hud'].speed={x=0,y=0}
		level.layers['hud'].repeated=false
		level.layers['hud'].cullingMethod=0
	else
		level.layers['hud'].cullingMethod=0 
	end
	level.layers['hud'].objects={} 
	objects = {
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['hud'], objProps ,level.assets)
		if (objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['hud'])
	--level.ldVersion=1.0.4	-- Level Director Version
	-- Parallax (after layers)
	level.canvasWidth=7680
	level.canvasHeight=800
	if level.parallaxEnabled then
		level.parallaxInfinite=true
		level.parallaxDamping=1
		instance:createParallax(level)
	end
	return level
end -- createLevel
return M

