-- Generated by Level Director X v1.0.4 on Mon Aug 1 12:11:38 2016 --
require("lib.LD_HelperX")
local M={}
-----------------------------------
function M:loadAssets()
-----------------------------------
	local assets={}
	assets.spriteSheetData={}
	assets.spriteSheetData['ms1_boat']={}
	assets.spriteSheetData['ms1_boat'].frames ={
		{x=1,y=1,width=317,height=208},
		{x=1,y=211,width=317,height=208},
		sheetContentWidth=512,
		sheetContentHeight=512
	}
	assets.spriteSheetData['ms1_waterA']={}
	assets.spriteSheetData['ms1_waterA'].frames ={
		{x=1,y=1,width=832,height=169},
		{x=1,y=172,width=832,height=169},
		{x=835,y=1,width=832,height=169},
		{x=835,y=172,width=832,height=169},
		sheetContentWidth=1668,
		sheetContentHeight=342
	}
	assets.spriteSheetData['ms1_waterB']={}
	assets.spriteSheetData['ms1_waterB'].frames ={
		{x=1,y=1,width=430,height=272},
		{x=1,y=1097,width=429,height=272},
		{x=1,y=275,width=430,height=272},
		{x=1,y=549,width=430,height=272},
		{x=1,y=823,width=430,height=272},
		{x=1,y=1371,width=429,height=272},
		sheetContentWidth=432,
		sheetContentHeight=1644
	}
	assets.spriteSheetData['ms1_wfall']={}
	assets.spriteSheetData['ms1_wfall'].frames ={
		{x=1,y=1,width=48,height=143},
		{x=51,y=1,width=32,height=139},
		sheetContentWidth=84,
		sheetContentHeight=145
	}
	assets.spriteSheetData['ms1_static']={}
	assets.spriteSheetData['ms1_static'].frames ={
		{x=1,y=196,width=153,height=86},
		{x=1,y=284,width=136,height=170},
		{x=139,y=284,width=101,height=170},
		{x=1,y=1,width=233,height=193},
		sheetContentWidth=241,
		sheetContentHeight=455
	}
	assets.spriteSheetData['ms_ufo']={}
	assets.spriteSheetData['ms_ufo'].frames ={
		{x=0,y=0,width=48,height=44},
		{x=50,y=0,width=48,height=44},
		{x=100,y=0,width=48,height=44},
		{x=150,y=0,width=48,height=44},
		{x=200,y=0,width=48,height=44},
		{x=250,y=0,width=48,height=44},
		{x=300,y=0,width=48,height=44},
		sheetContentWidth=396,
		sheetContentHeight=44
	}
	assets.spriteSheetData['ms_gwater']={}
	assets.spriteSheetData['ms_gwater'].frames ={
		{x=0,y=0,width=350,height=48},
		{x=0,y=51,width=350,height=48},
		{x=0,y=102,width=350,height=48},
		{x=0,y=153,width=350,height=48},
		sheetContentWidth=350,
		sheetContentHeight=202
	}
	assets.spriteSheetData['ms_gwater2']={}
	assets.spriteSheetData['ms_gwater2'].frames ={
		{x=0,y=0,width=1655,height=51},
		{x=0,y=51,width=1655,height=51},
		{x=0,y=102,width=1655,height=51},
		{x=0,y=153,width=1655,height=51},
		sheetContentWidth=1655,
		sheetContentHeight=205
	}
	assets.spriteSheetData['ms1_chopperl']={}
	assets.spriteSheetData['ms1_chopperl'].frames ={
		{x=1,y=1,width=86,height=62},
		{x=89,y=1,width=84,height=61},
		{x=250,y=1,width=78,height=60},
		{x=175,y=1,width=73,height=61},
		sheetContentWidth=329,
		sheetContentHeight=64
	}
	assets.spriteSheetData['ms1_blades']={}
	assets.spriteSheetData['ms1_blades'].frames ={
		{x=0,y=0,width=84,height=27},
		{x=84,y=0,width=84,height=27},
		{x=168,y=0,width=84,height=27},
		{x=252,y=0,width=84,height=27},
		sheetContentWidth=336,
		sheetContentHeight=27
	}
	assets.spriteSheetData['ms1_soldierl']={}
	assets.spriteSheetData['ms1_soldierl'].frames ={
		{x=1,y=125,width=20,height=38},
		{x=25,y=124,width=20,height=40},
		{x=27,y=42,width=23,height=40},
		{x=1,y=1,width=26,height=39},
		{x=83,y=1,width=24,height=38},
		{x=52,y=81,width=22,height=38},
		{x=49,y=121,width=21,height=38},
		{x=76,y=81,width=21,height=40},
		{x=1,y=82,width=22,height=41},
		{x=29,y=1,width=25,height=39},
		{x=25,y=84,width=22,height=38},
		{x=108,y=41,width=19,height=38},
		{x=56,y=41,width=24,height=38},
		{x=82,y=41,width=24,height=38},
		{x=56,y=1,width=25,height=38},
		{x=1,y=42,width=24,height=38},
		sheetContentWidth=128,
		sheetContentHeight=256
	}
	assets.spriteSheetData['ms1_soldier2']={}
	assets.spriteSheetData['ms1_soldier2'].frames ={
		{x=0,y=0,width=67,height=31},
		{x=67,y=0,width=67,height=31},
		{x=134,y=0,width=67,height=31},
		{x=201,y=0,width=67,height=31},
		sheetContentWidth=269,
		sheetContentHeight=31
	}
	assets.spriteSheetData['ms1_soldier_hang']={}
	assets.spriteSheetData['ms1_soldier_hang'].frames ={
		{x=0,y=0,width=26,height=51},
		{x=26,y=0,width=26,height=51},
		{x=52,y=0,width=26,height=51},
		{x=78,y=0,width=26,height=51},
		{x=104,y=0,width=26,height=51},
		sheetContentWidth=131,
		sheetContentHeight=51
	}
	assets.spriteSheetData['ms1_soldier_float']={}
	assets.spriteSheetData['ms1_soldier_float'].frames ={
		{x=0,y=0,width=46,height=49},
		{x=46,y=0,width=46,height=49},
		{x=92,y=0,width=46,height=49},
		{x=138,y=0,width=46,height=49},
		sheetContentWidth=184,
		sheetContentHeight=49
	}
	assets['mgs_bg1_0']={file ='mgs_bg1.png',name='mgs_bg1_0',class='',aX=0.5,aY=0.5,width=4151,height=238,frame=0,spriteSheetName='mgs_bg1',frameCount=1,
		 }
	assets['ms_bga_0']={file ='ms_bga.png',name='ms_bga_0',class='',aX=0.5,aY=0.5,width=1180,height=176,frame=0,spriteSheetName='ms_bga',frameCount=1,
		 }
	assets['ms_boat1_png']={file ='ms1_boat.png',name='ms_boat1_png',class='',aX=0.5,aY=0.5,width=317,height=208,frame=1,spriteSheetName='ms1_boat',frameCount=2,
		sequenceData={{name='sequence 1',frames={ 1,2 },time =400,loopCount=0,loopDirection='forward' },},
		sequenceInfo={default='sequence 1',play=true },
		 }
	assets['slice34_34_png']={file ='ms1_waterA.png',name='slice34_34_png',class='',aX=0.5,aY=0.5,width=832,height=169,frame=1,spriteSheetName='ms1_waterA',frameCount=4,
		sequenceData={{name='sequence 1',frames={ 1,2,3,4 },time =400,loopCount=0,loopDirection='forward' },},
		sequenceInfo={default='sequence 1',play=true },
		 }
	assets['slice26_26_png']={file ='ms1_waterB.png',name='slice26_26_png',class='',aX=0.5,aY=0.5,width=430,height=272,frame=1,spriteSheetName='ms1_waterB',frameCount=6,
		sequenceData={{name='sequence 1',frames={ 1,3,4,5 },time =400,loopCount=0,loopDirection='forward' },},
		sequenceInfo={default='sequence 1',play=true },
		 }
	assets['ms_fall1_png']={file ='ms1_wfall.png',name='ms_fall1_png',class='',aX=0.5,aY=0.5,width=48,height=143,frame=1,spriteSheetName='ms1_wfall',frameCount=2,
		sequenceData={{name='sequence 1',frames={ 1 },time =400,loopCount=0,loopDirection='forward' },},
		sequenceInfo={default='sequence 1',play=true },
		 }
	assets['ms1_fg1_png']={file ='ms1_static.png',name='ms1_fg1_png',class='',aX=0.5,aY=0.5,width=153,height=86,frame=1,spriteSheetName='ms1_static',frameCount=4,
		 }
	assets['ms1_hut_png']={file ='ms1_static.png',name='ms1_hut_png',class='',aX=0.5,aY=0.5,width=136,height=170,frame=2,spriteSheetName='ms1_static',frameCount=4,
		 }
	assets['ms1_hut2_png']={file ='ms1_static.png',name='ms1_hut2_png',class='',aX=0.5,aY=0.5,width=101,height=170,frame=3,spriteSheetName='ms1_static',frameCount=4,
		 }
	assets['ms1_hut3_png']={file ='ms1_static.png',name='ms1_hut3_png',class='',aX=0.5,aY=0.5,width=233,height=193,frame=4,spriteSheetName='ms1_static',frameCount=4,
		 }
	assets['ms_ufo_1']={file ='ms_ufo.png',name='ms_ufo_1',class='',aX=0.5,aY=0.5,width=48,height=44,frame=2,spriteSheetName='ms_ufo',frameCount=7,
		 }
	assets['ms_gwater_0']={file ='ms_gwater.png',name='ms_gwater_0',class='',aX=0.5,aY=0.5,width=350,height=48,frame=1,spriteSheetName='ms_gwater',frameCount=4,
		sequenceData={{name='sequence 1',frames={ 1,2,4,2 },time =500,loopCount=0,loopDirection='forward' },},
		sequenceInfo={default='sequence 1',play=true },
		 }
	assets['ms_gwater2_0']={file ='ms_gwater2.png',name='ms_gwater2_0',class='',aX=0.5,aY=0.5,width=1655,height=51,frame=1,spriteSheetName='ms_gwater2',frameCount=4,
		sequenceData={{name='sequence 1',frames={ 1,2,3,4 },time =400,loopCount=0,loopDirection='forward' },},
		sequenceInfo={default='sequence 1',play=true },
		 }
	assets['ms1_clouds_0']={file ='ms1_clouds.png',name='ms1_clouds_0',class='',aX=0.5,aY=0.5,width=433,height=62,frame=0,spriteSheetName='ms1_clouds',frameCount=1,
		 }
	assets['ms1_chop1_png']={file ='ms1_chopperl.png',name='ms1_chop1_png',class='',aX=0.5,aY=0.5,width=86,height=62,frame=1,spriteSheetName='ms1_chopperl',frameCount=4,
		sequenceData={{name='sequence1',frames={ 1,2,3,4,4,3,2,1 },time =1300,loopCount=0,loopDirection='forward' },},
		sequenceInfo={default='sequence1',play=false },
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=true,isSleepingAllowed=false,isSensor=true,isBullet=false,shapes={{bodyShape='Rectangle',shape={},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,linearDamping=0,angularDamping=0,gravityScale=1,groupIndex=0},}	}  }
	assets['ms1_blades_0']={file ='ms1_blades.png',name='ms1_blades_0',class='',aX=0.5,aY=0.5,width=84,height=27,frame=1,spriteSheetName='ms1_blades',frameCount=4,
		sequenceData={{name='sequence 1',frames={ 1,2,3,4 },time =100,loopCount=0,loopDirection='forward' },},
		sequenceInfo={default='sequence 1',play=true },
		physics={isEnabled=true,source='Asset',bodyType='dynamic',isFixedRotation=true,isSleepingAllowed=false,isSensor=true,isBullet=false,shapes={{bodyShape='Rectangle',shape={},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,linearDamping=0,angularDamping=0,gravityScale=1,groupIndex=0},}	}  }
	assets['Image1_01_png']={file ='ms1_soldierl.png',name='Image1_01_png',class='',aX=0.5,aY=0.5,width=20,height=38,frame=1,spriteSheetName='ms1_soldierl',frameCount=16,
		sequenceData={{name='run',frames={ 1,2,3,4,5,6,7,8,9,10,11,12 },time =800,loopCount=0,loopDirection='forward' },{name='sequence 2',frames={  },time =600,loopCount=0,loopDirection='forward' },},
		sequenceInfo={default='run',play=true },
		physics={isEnabled=true,source='Asset',bodyType='kinematic',isFixedRotation=false,isSleepingAllowed=false,isSensor=true,isBullet=false,shapes={{bodyShape='Rectangle',shape={},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,linearDamping=0,angularDamping=0,gravityScale=1,groupIndex=0},}	}  }
	assets['ms1_soldier2_0']={file ='ms1_soldier2.png',name='ms1_soldier2_0',class='',aX=0.5,aY=0.5,width=67,height=31,frame=1,spriteSheetName='ms1_soldier2',frameCount=4,
		sequenceData={{name='sequence 1',frames={ 1,2,3 },time =800,loopCount=0,loopDirection='forward' },},
		sequenceInfo={default='sequence 1',play=true },
		 }
	assets['ms1_soldier_hang_0']={file ='ms1_soldier_hang.png',name='ms1_soldier_hang_0',class='',aX=0.5,aY=0.5,width=26,height=51,frame=1,spriteSheetName='ms1_soldier_hang',frameCount=5,
		sequenceData={{name='sequence 1',frames={ 1,2,3,4,5 },time =1000,loopCount=0,loopDirection='forward' },},
		sequenceInfo={default='sequence 1',play=true },
		 }
	assets['ms1_soldier_float_0']={file ='ms1_soldier_float.png',name='ms1_soldier_float_0',class='',aX=0.5,aY=0.5,width=46,height=49,frame=1,spriteSheetName='ms1_soldier_float',frameCount=4,
		sequenceData={{name='sequence 1',frames={ 1,2,3,2 },time =1200,loopCount=0,loopDirection='forward' },},
		sequenceInfo={default='sequence 1',play=true },
		 }
	return assets
end -- loadAssets 

------------------------------------------
function M:createLevel(LD_Helper_Instance)
------------------------------------------
	local instance=LD_Helper_Instance
	local objProps={}
	local level={}
    local obj=nil
	local k=0
	local objects = nil 
	if (instance.viewGroup == nil) then
		level.view=display.newGroup() 
	else
		level.view=instance.viewGroup
	end
	level.view.anchorChildren =false 
	display.setDefault( 'background',181/255,203/255,222/255,222/255)
	display.setDefault( "anchorX",0.5 )
	display.setDefault( "anchorY",0.5 )	
	display.setDrawMode("wireframe",false)
	level.name='scene2_view' 
	-- Load Assets
	level.assets=self:loadAssets()
	-- Physics properties
	physics.setGravity(0,9.8) 
	physics.setDrawMode('normal')
	physics.setPositionIterations(8)	
	physics.setVelocityIterations(3)	
	level.parallaxEnabled=true
	-- Layers --
	level.layers={} 
	---- stage3_bg ------------------------------------------------------------------------------------
	level.layers['stage3_bg']={} 
	level.layers['stage3_bg'].view=display.newGroup() 
	level.layers['stage3_bg'].name='stage3_bg' 
	if (level.parallaxEnabled) then
		level.layers['stage3_bg'].speed={x=0.8,y=0}
		level.layers['stage3_bg'].repeated=false
		level.layers['stage3_bg'].cullingMethod=0
	else
		level.layers['stage3_bg'].cullingMethod=0 
	end
	level.layers['stage3_bg'].objects={} 
	objects = {
	{name='ms_bgb_1',objType='LDImage',class='',width=1032,height=608,x=7516,y=256,xScale=3.25552*1,yScale=2.92308*1,assetName='ms_boat1_png',
		userProps = {},
		},
	{name='ms1_clouds_2',objType='LDImage',class='',width=1600,height=352,x=2720,y=160,xScale=3.69515*1,yScale=5.67742*1,assetName='ms1_clouds_0',
		userProps = {},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['stage3_bg'], objProps ,level.assets)
		if (objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['stage3_bg'])
	---- stage2_bg ------------------------------------------------------------------------------------
	level.layers['stage2_bg']={} 
	level.layers['stage2_bg'].view=display.newGroup() 
	level.layers['stage2_bg'].name='stage2_bg' 
	if (level.parallaxEnabled) then
		level.layers['stage2_bg'].speed={x=0.9,y=0}
		level.layers['stage2_bg'].repeated=false
		level.layers['stage2_bg'].cullingMethod=0
	else
		level.layers['stage2_bg'].cullingMethod=0 
	end
	level.layers['stage2_bg'].objects={} 
	objects = {
	{name='ms_bga_1',objType='LDImage',class='',width=3488,height=560,x=6672,y=280,xScale=2.95593*1,yScale=3.18182*1,assetName='ms_bga_0',
		userProps = {},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['stage2_bg'], objProps ,level.assets)
		if (objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['stage2_bg'])
	---- main ------------------------------------------------------------------------------------
	level.layers['main']={} 
	level.layers['main'].view=display.newGroup() 
	level.layers['main'].name='main' 
	if (level.parallaxEnabled) then
		level.layers['main'].speed={x=1,y=0}
		level.layers['main'].repeated=false
		level.layers['main'].cullingMethod=0
	else
		level.layers['main'].cullingMethod=0 
	end
	level.layers['main'].objects={} 
	objects = {
	{name='ms_gwater_5',objType='LDImage',class='',width=1079.5,height=189.333,x=9847,y=559,xScale=3.08429*1,yScale=3.94444*1,assetName='ms_gwater_0',
		userProps = {},
		},
	{name='mgs_bg1_1',objType='LDImage',class='',width=11520,height=688,x=0,y=-48,xScale=2.77523*1,yScale=2.89076*1,assetName='mgs_bg1_0',
		rotation=0,enableDrag=false,anchorX=0,anchorY=0,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='ms_gwater2_6',objType='LDImage',class='',width=4595,height=143,x=7453,y=575,xScale=2.77644*1,yScale=2.80392*1,assetName='ms_gwater2_0',
		userProps = {},
		},
	{name='slice26_26_3',objType='LDImage',class='',width=1088,height=736,x=9824,y=176,xScale=2.53023*1,yScale=2.70588*1,assetName='slice26_26_png',
		userProps = {},
		},
	{name='slice34_34_2',objType='LDImage',class='',width=2304,height=496,x=10368,y=408,xScale=2.76923*1,yScale=2.93491*1,assetName='slice34_34_png',
		userProps = {},
		},
	{name='ms_fall1_4',objType='LDImage',class='',width=134,height=304,x=10137,y=8,xScale=2.79167*1,yScale=2.12587*1,assetName='ms_fall1_png',
		userProps = {},
		},
	{name='ms1_hut2_7',objType='LDImage',class='',width=277,height=304,x=8059,y=372,xScale=2.74257*1,yScale=1.78824*1,assetName='ms1_hut2_png',
		userProps = {},
		},
	{name='ms1_hut_8',objType='LDImage',class='',width=369,height=320,x=7895,y=376,xScale=2.71324*1,yScale=1.88235*1,assetName='ms1_hut_png',
		userProps = {},
		},
	{name='ms1_hut3_9',objType='LDImage',class='',width=642,height=423,x=8511,y=322,xScale=2.75536*1,yScale=2.19171*1,assetName='ms1_hut3_png',
		userProps = {},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['main'], objProps ,level.assets)
		if (objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['main'])
	---- enemy ------------------------------------------------------------------------------------
	level.layers['enemy']={} 
	level.layers['enemy'].view=display.newGroup() 
	level.layers['enemy'].name='enemy' 
	if (level.parallaxEnabled) then
		level.layers['enemy'].speed={x=1,y=0}
		level.layers['enemy'].repeated=false
		level.layers['enemy'].cullingMethod=0
	else
		level.layers['enemy'].cullingMethod=0 
	end
	level.layers['enemy'].objects={} 
	objects = {
	{name='chopper_1',objType='LDImage',class='',width=182,height=118,x=4708,y=-67,xScale=2.11628*1,yScale=1.90323*1,assetName='ms1_chop1_png',
		userProps = {},
		},
	{name='bezier_2',objType='LDBezier',class='',width=24,height=24,x=4792,y=160,xScale=1*1,yScale=1*1,assetName='',
		rotation=0,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=false,blendMode='normal',
		styleProps={radius=12,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=255/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		pointProps={outputType='Display',xPoints={53,66,68,160,224,93,-33,-225},yPoints={ -51,-39,-40,-30,-8,35,50,34}},
		userProps = {},
		},
	{name='chopper_path_2',objType='LDFPath',class='',width=181,height=1,x=4767,y=27,xScale=1*1,yScale=1*1,assetName='',
		pointProps={outputType='Display',xPoints={-79,79},yPoints={ -84,83}},
		followPathProps={srcObj='chopper_1',path='bezier_2',direction=1,rotate=false,rebound=true,repeats=3,delay=3,autoStart=false,xFlip=false,yFlip=false},
		userProps = {},
		},
	{name='chopper_1_blades',objType='LDImage',class='',width=197,height=49,x=4687,y=-117,xScale=2.34524*1,yScale=1.81481*1,assetName='ms1_blades_0',
		userProps = {},
		},
	{name='joint_5',objType='LDJoint',class='',width=20,height=50,x=4698,y=-92,xScale=1*1,yScale=1*1,assetName='',
		jointProps={jointType='distance',srcObjectName='chopper_1_blades',anchorA={x=4693,y=-116 },dstObjectName='chopper_1',anchorB={x=4692,y=-116 },paramA=0,paramB=0,motorSpeed=0,maxMotorTorque=0,limit1=0,limit2=0,limitEnabled=false,motorEnabled =false},
		userProps = {},
		},
	{name='path_6',objType='LDPath',class='',width=24,height=24,x=4755,y=5,xScale=1*1,yScale=1*1,assetName='',
		rotation=0,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=false,blendMode='normal',
		styleProps={radius=12,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=255/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		pointProps={outputType='Display',xPoints={89,-22,-76,-90,-59},yPoints={ 104,83,55,33,-105}},
		userProps = {},
		},
	{name='chopper_path_1',objType='LDFPath',class='',width=12,height=3,x=4777,y=30,xScale=1*1,yScale=1*1,assetName='',
		pointProps={outputType='Display',xPoints={-83,82},yPoints={ -89,88}},
		followPathProps={srcObj='chopper_1',path='path_6',direction=-1,rotate=false,rebound=false,repeats=0,delay=8,autoStart=false,xFlip=false,yFlip=false},
		userProps = {},
		},
	{name='soldier_1',objType='LDImage',class='Enemy',width=48,height=70,x=1829,y=484,xScale=2.4*1,yScale=1.84211*1,assetName='Image1_01_png',
		rotation=0,enableDrag=false,anchorX=0.5,anchorY=1,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='path_1',objType='LDPath',class='',width=24,height=24,x=1263,y=482,xScale=1*1,yScale=1*1,assetName='',
		rotation=0,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=false,blendMode='normal',
		styleProps={radius=12,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=255/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		pointProps={outputType='Display',xPoints={563,472,345,188,-41,-211,-563},yPoints={ -3,3,-2,-1,1,2,1}},
		userProps = {},
		},
	{name='soldier_fpath_1',objType='LDFPath',class='',width=7,height=33,x=1832,y=465,xScale=1*1,yScale=1*1,assetName='',
		pointProps={outputType='Display',xPoints={-4,3},yPoints={ -17,16}},
		followPathProps={srcObj='soldier_1',path='path_1',direction=1,rotate=false,rebound=true,repeats=2,delay=8,autoStart=true,xFlip=true,yFlip=false},
		userProps = {},
		},
	{name='soldier_2',objType='LDImage',class='',width=48,height=70,x=4170,y=576,xScale=2.4*1,yScale=1.84211*1,assetName='Image1_01_png',
		rotation=0,enableDrag=false,anchorX=0.5,anchorY=1,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='path_12',objType='LDPath',class='',width=24,height=24,x=3937,y=562,xScale=1*1,yScale=1*1,assetName='',
		rotation=0,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=false,blendMode='normal',
		styleProps={radius=12,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=255/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		pointProps={outputType='Display',xPoints={250,138,-6,-86,-250},yPoints={ -1,-8,4,1,8}},
		userProps = {},
		},
	{name='follow_path_13',objType='LDFPath',class='',width=29,height=32,x=4185,y=557,xScale=1*1,yScale=1*1,assetName='',
		pointProps={outputType='Display',xPoints={-15,14},yPoints={ -16,16}},
		followPathProps={srcObj='soldier_2',path='path_12',direction=1,rotate=false,rebound=true,repeats=-1,delay=8,autoStart=true,xFlip=true,yFlip=false},
		userProps = {},
		},
	{name='ms1_soldier2_14',objType='LDImage',class='',width=142,height=77,x=5789,y=334,xScale=2.1194*1,yScale=2.48387*1,assetName='ms1_soldier2_0',
		userProps = {},
		},
	{name='ms1_soldier2_15',objType='LDImage',class='',width=142,height=77,x=6816,y=195,xScale=2.1194*1,yScale=2.48387*1,assetName='ms1_soldier2_0',
		userProps = {},
		},
	{name='ms1_soldier_hang_16',objType='LDImage',class='',width=58,height=101,x=7498,y=312,xScale=2.23077*1,yScale=1.98039*1,assetName='ms1_soldier_hang_0',
		userProps = {},
		},
	{name='ms1_soldier_float_17',objType='LDImage',class='',width=103,height=74,x=8485,y=545,xScale=2.23913*1,yScale=1.5102*1,assetName='ms1_soldier_float_0',
		userProps = {},
		},
	{name='path_18',objType='LDPath',class='',width=24,height=24,x=8290,y=557,xScale=1*1,yScale=1*1,assetName='',
		rotation=0,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=false,blendMode='normal',
		styleProps={radius=12,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=255/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		pointProps={outputType='Display',xPoints={191,-11,-192},yPoints={ -1,0,1}},
		userProps = {},
		},
	{name='follow_path_19',objType='LDFPath',class='',width=10,height=19,x=8490,y=555,xScale=1*1,yScale=1*1,assetName='',
		pointProps={outputType='Display',xPoints={-6,5},yPoints={ -10,9}},
		followPathProps={srcObj='ms1_soldier_float_17',path='path_18',direction=1,rotate=false,rebound=true,repeats=-1,delay=15,autoStart=true,xFlip=true,yFlip=false},
		userProps = {},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['enemy'], objProps ,level.assets)
		if (objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['enemy'])
	---- player ------------------------------------------------------------------------------------
	level.layers['player']={} 
	level.layers['player'].view=display.newGroup() 
	level.layers['player'].name='player' 
	if (level.parallaxEnabled) then
		level.layers['player'].speed={x=0,y=0}
		level.layers['player'].repeated=false
		level.layers['player'].cullingMethod=0
	else
		level.layers['player'].cullingMethod=0 
	end
	level.layers['player'].objects={} 
	objects = {
	{name='ms_ufo',objType='LDImage',class='',width=72,height=66,x=507,y=327,xScale=1.5*1,yScale=1.5*1,assetName='ms_ufo_1',
		userProps = {},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['player'], objProps ,level.assets)
		if (objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['player'])
	---- FG ------------------------------------------------------------------------------------
	level.layers['FG']={} 
	level.layers['FG'].view=display.newGroup() 
	level.layers['FG'].name='FG' 
	if (level.parallaxEnabled) then
		level.layers['FG'].speed={x=1,y=0}
		level.layers['FG'].repeated=false
		level.layers['FG'].cullingMethod=0
	else
		level.layers['FG'].cullingMethod=0 
	end
	level.layers['FG'].objects={} 
	objects = {
	{name='ms1_fg1_1',objType='LDImage',class='',width=424,height=255,x=3978,y=480,xScale=2.77124*1,yScale=2.96512*1,assetName='ms1_fg1_png',
		userProps = {},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['FG'], objProps ,level.assets)
		if (objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['FG'])
	---- hud ------------------------------------------------------------------------------------
	level.layers['hud']={} 
	level.layers['hud'].view=display.newGroup() 
	level.layers['hud'].name='hud' 
	if (level.parallaxEnabled) then
		level.layers['hud'].speed={x=0,y=0}
		level.layers['hud'].repeated=false
		level.layers['hud'].cullingMethod=0
	else
		level.layers['hud'].cullingMethod=0 
	end
	level.layers['hud'].objects={} 
	objects = {
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['hud'], objProps ,level.assets)
		if (objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['hud'])
	---- markers ------------------------------------------------------------------------------------
	level.layers['markers']={} 
	level.layers['markers'].view=display.newGroup() 
	level.layers['markers'].name='markers' 
	if (level.parallaxEnabled) then
		level.layers['markers'].speed={x=0,y=0}
		level.layers['markers'].repeated=false
		level.layers['markers'].cullingMethod=0
	else
		level.layers['markers'].cullingMethod=0 
	end
	level.layers['markers'].objects={} 
	objects = {
	{name='stage_1',objType='LDMarker',class='stage',width=32,height=32,x=5088,y=352,xScale=1*1,yScale=1*1,assetName='',
		rotation=0,enableDrag=false,anchorX=0,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'isActive', value='true' },{name= 'scrollPause', value='true' },},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['markers'], objProps ,level.assets)
		if (objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['markers'])
	--level.ldVersion=1.0.4	-- Level Director Version
	-- Parallax (after layers)
	level.canvasWidth=11520
	level.canvasHeight=640
	if level.parallaxEnabled then
		level.parallaxInfinite=false
		level.parallaxDamping=10
		instance:createParallax(level)
	end
	return level
end -- createLevel
return M

