-- Generated by Level Director X v1.1.0 on mar set 17 16:12:23 2019 --
require("lib.LD_HelperX")
local M={}
-----------------------------------
function M:loadAssets()
-----------------------------------
	local assets={}
	assets.spriteSheetData={}
	return assets
end -- loadAssets 

------------------------------------------
function M:createLevel(LD_Helper_Instance)
------------------------------------------
	local instance=LD_Helper_Instance
	local objProps={}
	local level={}
    local obj=nil
	local k=0
	local objects = nil 
	if (instance.viewGroup == nil) then
		level.view=display.newGroup() 
	else
		level.view=instance.viewGroup
	end
	level.view.anchorChildren =false 
	display.setDefault( 'background',128/255,128/255,128/255,255/255)
	display.setDefault( "anchorX",0.5 )
	display.setDefault( "anchorY",0.5 )	
	display.setDrawMode("wireframe",false)
	level.name='Level01' 
	-- Load Assets
	level.assets=self:loadAssets()
	-- Physics properties
	physics.setGravity(0,9.8) 
	physics.setDrawMode('normal')
	physics.setPositionIterations(8)	
	physics.setVelocityIterations(3)	
	level.parallaxEnabled=false
	-- Layers --
	level.layers={} 
	---- Layer1 ------------------------------------------------------------------------------------
	level.layers['Layer1']={} 
	level.layers['Layer1'].view=display.newGroup() 
	level.layers['Layer1'].name='Layer1' 
	if (level.parallaxEnabled) then
		level.layers['Layer1'].speed={x=0,y=0}
		level.layers['Layer1'].repeated=false
		level.layers['Layer1'].cullingMethod=0
	else
		level.layers['Layer1'].cullingMethod=0 
	end
	level.layers['Layer1'].objects={} 
	objects = {
	{name='track',objType='LDPolygon',class='',width=912,height=384,x=488,y=432,xScale=1*1,yScale=1*1,assetName='',
		styleProps={radius=0,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=255/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=50/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=50/255},
		pointProps={outputType='Display',xPoints={8,456,8,-184,-456,-456},yPoints={ -192,-96,-64,192,-48,-96}},
		userProps = {},
		},
	{name='zigzag',objType='LDPath',class='',width=832,height=96,x=512,y=80,xScale=1*1,yScale=1*1,assetName='',
		styleProps={radius=0,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=255/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		pointProps={outputType='Display',xPoints={416,-128,-192,-304,-416},yPoints={ 48,48,-48,48,48}},
		userProps = {},
		},
	{name='ball',objType='LDEllipse',class='',width=32,height=32,x=64,y=608,xScale=1*1,yScale=1*1,assetName='',
		styleProps={radius=16,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=255/255,fillColorR=255/255,fillColorG=0/255,fillColorB=0/255,fillColorA=255/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=255/255,fillColorG=0/255,fillColorB=0/255,fillColorA=255/255},
		userProps = {},
		},
	{name='ball_12',objType='LDEllipse',class='',width=32,height=32,x=48,y=176,xScale=1*1,yScale=1*1,assetName='',
		styleProps={radius=16,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=255/255,fillColorR=255/255,fillColorG=0/255,fillColorB=0/255,fillColorA=255/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=255/255,fillColorG=0/255,fillColorB=0/255,fillColorA=255/255},
		userProps = {},
		},
	{name='follow_path_13',objType='LDFPath',class='',width=48,height=48,x=72,y=152,xScale=1*1,yScale=1*1,assetName='',
		pointProps={outputType='Display',xPoints={-24,24},yPoints={ 24,-24}},
		followPathProps={srcObj='ball_12',path='zigzag',direction=-1,rotate=false,rebound=true,repeats=-1,delay=10,autoStart=true,xFlip=false,yFlip=false},
		userProps = {},
		},
	{name='follow_path_11',objType='LDFPath',class='',width=432,height=368,x=280,y=424,xScale=1*1,yScale=1*1,assetName='',
		pointProps={outputType='Display',xPoints={-216,216},yPoints={ 184,-184}},
		followPathProps={srcObj='ball',path='track',direction=1,rotate=false,rebound=false,repeats=-1,delay=2,autoStart=false,xFlip=false,yFlip=false},
		userProps = {},
		},
	{name='polygon_7',objType='LDPolygon',class='',width=352,height=80,x=686,y=536,xScale=1*1,yScale=1*1,assetName='',
		rotation=0,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=0,isVisible=true,blendMode='normal',
		styleProps={radius=12,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=255/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		pointProps={outputType='Display',xPoints={-176,-32,176},yPoints={ -40,40,-24}},
		userProps = {},
		},
	{name='ellipse_8',objType='LDEllipse',class='',width=32,height=32,x=466,y=39,xScale=1*1,yScale=1*1,assetName='',
		styleProps={radius=16,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=255/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		userProps = {},
		},
	{name='follow_path_9',objType='LDFPath',class='',width=56,height=469,x=494,y=274,xScale=1*1,yScale=1*1,assetName='',
		pointProps={outputType='Display',xPoints={-28,28},yPoints={ -235,234}},
		followPathProps={srcObj='ellipse_8',path='polygon_7',direction=1,rotate=false,rebound=false,repeats=-1,delay=1,autoStart=true,xFlip=false,yFlip=false},
		userProps = {},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['Layer1'], objProps ,level.assets)
		if (obj and objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['Layer1'])
	--level.ldVersion=1.1.0	-- Level Director Version
	-- Parallax (after layers)
	level.canvasWidth=960
	level.canvasHeight=640
	if level.parallaxEnabled then
		level.parallaxInfinite=false
		level.parallaxDamping=1
		instance:createParallax(level)
	end
	return level
end -- createLevel
return M

